/*


MONGODB Atlas screen after choocing MO free tear while creating NewProject in MONGODB Atlas

Add a connection IP address
    Your current IP address (223.185.132.239) has been added to enable local connectivity. Add another later in 
Network Access
.
Create a database user
    This first user will have atlasAdmin  permissions for this project.

    We autogenerated a username and password. You can use this or create your own.

You'll need your database user's credentials in the next step. Copy the database user password.
    Username: kmanu00005
    Password : ovRlL7UQlgqujYQp
Hide

________________________________________________________________

Connecting with MongoDB Driver
1. Select your driver and version
    We recommend installing and using the latest driver version.

    Driver Version

2. Install your driver-> Run the following on the command line ---->  npm install mongodb

View MongoDB Node.js Driver installation instructions.
3. Add your connection string into your application code
Use this connection string in your application


View full code sample -> mongodb connection String get from MongoDB Atlas

    mongodb+srv://kmanu00005:<password>@cluster0.co7yrow.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

Replace <password> with the password for the kmanu00005 user. Ensure any option params are URL encoded
.
*/

const express = require("express");
const fs = require("fs");

const app = express();
const PORT = 8002;

//Middleware

//if we are using urlencoded data format in POSTMAN for post method then we need to use express.urlencoded() for saving
app.use(express.urlencoded());
//if we are using raw data format in POSTMAN for post method then we need to use express.json() for saving
app.use(express.json());

const products = require("./MOCK_DATA.json");

// MongoDB Connection
const mongoose = require("mongoose");

// mongoose.connect('Pass the MongoDb connection string')
// mongoose.connect(
//   "mongodb+srv://kmanu00005:<password>@cluster0.co7yrow.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
// ); Password is the password that is generated while creating the cluster/new Project in the MongoDB Atlas
// mongoose.connect(
//   "mongodb+srv://kmanu00005:ovRlL7UQlgqujYQp@cluster0.co7yrow.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
// ); // this connect method will return a promise that need to be resolves/handled

mongoose
  .connect(
    "mongodb+srv://kmanu00005:ovRlL7UQlgqujYQp@cluster0.co7yrow.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  )
  .then(() => {
    console.log("Db connection established");
  })
  .catch((err) => {
    console.log("Error connecting:" + err);
  });

app.get("/api/products/", (req, res) => {
  console.log(req.params);
  //console.log(req.params.name);
  return res.json(products);
});

// Route Parameters
app.get("/api/products/:id", (req, res) => {
  //const { id } = req.params; // Destructuring the id from req.params -> OR convert the id to Number or while comparing convert id to parseInt(id)
  const id = Number(req.params.id);
  console.log(req.params.id);

  const product = products.find((product) => product.id === id);

  if (product) {
    return res.json(product);
  } else {
    return res.status(404).json({ message: "Product not found" });
  }
});

//POST
//After using middleware we can see the data in console.log after sending the request from POSTMAN
app.post("/api/products", (req, res) => {
  console.log(req.body);
  const newData = req.body;
  //products.push(newData);
  products.push({ id: products.length + 1, ...newData });

  fs.writeFile("./MOCK_DATA.json", JSON.stringify(products), (err, data) => {
    if (err) {
      return res
        .status(500)
        .json({ status: "error", message: "Error writing" });
    }
    return res.send({
      status: "Successful",
      id: products.length,
    });
  });
});

//Clean PUT methods
app.put("/api/products/:id", (req, res) => {
  const id = Number(req.params.id); // getting the id of resource
  const productIndex = products.findIndex((product) => product.id === id); //getting the productIndex from the database/resource here MOCK_DATA by comparing the id

  const body = req.body;
  products[productIndex] = { id: id, ...body }; // Create the updated product with the original ID coming first

  //now update the product
  fs.writeFile("./MOCK_DATA.json", JSON.stringify(products), (err, data) => {
    if (err) {
      return res
        .status(500)
        .json({ status: "error", message: "Error updating product" });
    }
    return res.json({ status: "success", id: id });
  });
});

//Delete

app.delete("/api/products/:id", (req, res) => {
  const id = Number(req.params.id); // Get the ID from the request parameters
  const productIndex = products.findIndex((product) => product.id === id);

  if (productIndex === -1) {
    return res
      .status(404)
      .json({ status: "error", message: "Product not found" });
  }

  // Remove the product from the array
  products.splice(productIndex, 1);

  // Write the updated array back to the file
  fs.writeFile("./MOCK_DATA.json", JSON.stringify(products, null, 2), (err) => {
    if (err) {
      return res
        .status(500)
        .json({ status: "error", message: "Error deleting product" });
    }
    return res.json({
      status: "success",
      message: "Product deleted successfully",
    });
  });
});

app.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
